// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the root Wails service: the bridge between the Go backend and the
 * frontend. It is intentionally thin — all real functionality lives in the
 * framework-agnostic packages under internal/ (core, library, opds…). Feature
 * services will be registered alongside it in later sessions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Ping is a health-check binding used to validate the full Go→JS chain: the
 * frontend calls it on load and renders the reply.
 */
export function Ping(): $CancellablePromise<$models.PingResult> {
    return $Call.ByID(1003072145);
}
