// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CalibreService controls the Calibre wireless (push) server that lets KOReader
 * connect over WiFi, and sends books to the connected device.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BookStates returns per-book presence information for the connected device, or
 * — when disconnected — for the last device seen, so the UI keeps showing which
 * books are on the reader from cache. Statuses refresh on the next connection.
 */
export function BookStates(ids: number[] | null): $CancellablePromise<$models.DeviceBookState[] | null> {
    return $Call.ByID(1092196108, ids);
}

/**
 * FetchReadingStats fetches KOReader's statistics database over the live
 * connection (dynamic path search), computes the reading aggregates and caches
 * them so the dashboard can show them offline. Refreshed each time it runs.
 */
export function FetchReadingStats(): $CancellablePromise<$models.ReadingStatsFetch> {
    return $Call.ByID(4234463762);
}

/**
 * ProbeReadingStats tries to fetch KOReader's `statistics.sqlite3` over the live
 * connection. It lives under `koreader/settings/`, OUTSIDE the Calibre inbox, so
 * we probe a handful of relative paths (KOReader's GET_BOOK_FILE_SEGMENT resolves
 * them under the inbox with no sanitising, so `..` traversal may reach it). This
 * confirms feasibility on real hardware before we build the full stats feature.
 */
export function ProbeReadingStats(): $CancellablePromise<$models.ReadingStatsProbe> {
    return $Call.ByID(3311387856);
}

/**
 * SendBooks pushes the given books to the connected device, honoring each
 * book's KOReader remote-path template/override (which may include subfolders).
 * Progress is emitted per book as "calibre:progress".
 */
export function SendBooks(ids: number[] | null): $CancellablePromise<$models.SendResult> {
    return $Call.ByID(1209648341, ids);
}

/**
 * SetEnabled starts or stops the push server and persists the preference.
 */
export function SetEnabled(enabled: boolean): $CancellablePromise<$models.CalibreStatus> {
    return $Call.ByID(4092251814, enabled);
}

/**
 * Status returns the current push-server and connection state.
 */
export function Status(): $CancellablePromise<$models.CalibreStatus> {
    return $Call.ByID(4218957489);
}

/**
 * SyncReadingFromDevice pulls KOReader reading progress and annotations over the
 * live Calibre connection — no USB needed. For every book Reliure has sent (per
 * the `.reliure` inventory) it requests the book's `.sdr` sidecar by lpath via
 * GET_BOOK_FILE_SEGMENT, parses it and stores progress + annotations. The
 * inventory maps each lpath to a book id, so matching is exact.
 */
export function SyncReadingFromDevice(): $CancellablePromise<$models.KoreaderSyncResult> {
    return $Call.ByID(1527324102);
}
