// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CalibreService controls the Calibre wireless (push) server that lets KOReader
 * connect over WiFi, and sends books to the connected device.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BookStates returns per-book presence information for the connected device.
 */
export function BookStates(ids: number[] | null): $CancellablePromise<$models.DeviceBookState[] | null> {
    return $Call.ByID(1092196108, ids);
}

/**
 * SendBooks pushes the given books to the connected device, honoring each
 * book's KOReader remote-path template/override (which may include subfolders).
 * Progress is emitted per book as "calibre:progress".
 */
export function SendBooks(ids: number[] | null): $CancellablePromise<$models.SendResult> {
    return $Call.ByID(1209648341, ids);
}

/**
 * SetEnabled starts or stops the push server and persists the preference.
 */
export function SetEnabled(enabled: boolean): $CancellablePromise<$models.CalibreStatus> {
    return $Call.ByID(4092251814, enabled);
}

/**
 * Status returns the current push-server and connection state.
 */
export function Status(): $CancellablePromise<$models.CalibreStatus> {
    return $Call.ByID(4218957489);
}
