// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KOReaderService mirrors reading progress and annotations from a KOReader
 * library into Reliure. It reads the reader's `.sdr` sidecars from a folder the
 * user points at — a USB-mounted device, or a synced copy of its library.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnnotatedBooks returns every book that has annotations, with its annotations,
 * for the dedicated "Annotations" view. Books are ordered by title.
 */
export function AnnotatedBooks(): $CancellablePromise<$models.AnnotatedBook[] | null> {
    return $Call.ByID(1915922466);
}

/**
 * ChooseFolderAndSync opens a native directory picker (rooted at the last folder
 * used), remembers the choice and syncs from it.
 */
export function ChooseFolderAndSync(): $CancellablePromise<$models.KoreaderSyncResult> {
    return $Call.ByID(3768933653);
}

/**
 * ReadingStates returns every book's reading state for grid badges/progress.
 */
export function ReadingStates(): $CancellablePromise<$models.ReadingCard[] | null> {
    return $Call.ByID(480056186);
}

/**
 * StatusCounts returns how many books sit in each reading status, for the
 * sidebar's reading filters.
 */
export function StatusCounts(): $CancellablePromise<$models.ReadingStatusCounts> {
    return $Call.ByID(4052219778);
}

/**
 * Sync re-scans the previously chosen folder.
 */
export function Sync(): $CancellablePromise<$models.KoreaderSyncResult> {
    return $Call.ByID(3594265519);
}
