// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService exposes library operations to the frontend: importing folders
 * of ebooks (with live progress events) and basic stats. It is a thin adapter
 * over internal/library and internal/core.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Authors returns the sidebar's author list with counts.
 */
export function Authors(): $CancellablePromise<$models.SidebarItem[] | null> {
    return $Call.ByID(2813498622);
}

/**
 * Book returns the full detail for one book.
 */
export function Book(id: number): $CancellablePromise<$models.BookDetail> {
    return $Call.ByID(1347111875, id);
}

/**
 * Books returns all books in the given sort order ("title", "author", "added").
 */
export function Books(sort: string): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(378021392, sort);
}

/**
 * BooksByAuthor returns an author's books.
 */
export function BooksByAuthor(id: number): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(240607566, id);
}

/**
 * BooksBySeries returns a series' books, in reading order.
 */
export function BooksBySeries(id: number): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(1453195768, id);
}

/**
 * BooksByTag returns the books carrying a tag.
 */
export function BooksByTag(id: number): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(2072736763, id);
}

/**
 * ChooseAndImport opens a native picker that accepts any mix of EPUB files and
 * folders (multiple selection), and imports them. Folders are scanned
 * recursively. Emits an "import:progress" event per file. An empty selection
 * (dialog cancelled) is a no-op.
 */
export function ChooseAndImport(): $CancellablePromise<$models.ImportSummary> {
    return $Call.ByID(1506731901);
}

/**
 * ImportPaths imports a mix of files and directories (directories are scanned
 * recursively) using the current import mode. It emits an "import:progress"
 * event per file and an "import:done" event with the summary at the end — the
 * latter lets a drag-and-drop import (which nothing awaits) refresh the view.
 */
export function ImportPaths(paths: string[] | null): $CancellablePromise<$models.ImportSummary> {
    return $Call.ByID(726455477, paths);
}

/**
 * Search returns books matching a full-text query, ranked by relevance.
 */
export function Search(query: string): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(2206755262, query);
}

/**
 * SeriesList returns the sidebar's series list with counts.
 */
export function SeriesList(): $CancellablePromise<$models.SidebarItem[] | null> {
    return $Call.ByID(812942751);
}

/**
 * Stats returns basic counts for the UI.
 */
export function Stats(): $CancellablePromise<$models.LibraryStats> {
    return $Call.ByID(2363876853);
}

/**
 * Tags returns the sidebar's tag list with counts.
 */
export function Tags(): $CancellablePromise<$models.SidebarItem[] | null> {
    return $Call.ByID(4025079207);
}
