// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService exposes library operations to the frontend: importing folders
 * of ebooks (with live progress events) and basic stats. It is a thin adapter
 * over internal/library and internal/core.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyOnlineMetadata persists the user's chosen fields (already merged into a
 * BookUpdate by the frontend) and, if a cover URL was chosen, downloads and
 * installs that cover. Cover failure is non-fatal: the metadata is the point,
 * so it is logged and the (metadata-updated) detail is still returned.
 */
export function ApplyOnlineMetadata($in: $models.ApplyMetadataInput): $CancellablePromise<$models.BookDetail> {
    return $Call.ByID(347221400, $in);
}

/**
 * AuthorGroups returns author tiles for the grouped library view, including a
 * synthetic fallback tile for books without authors.
 */
export function AuthorGroups(): $CancellablePromise<$models.SidebarItem[] | null> {
    return $Call.ByID(2765419737);
}

/**
 * Authors returns the sidebar's author list with counts.
 */
export function Authors(): $CancellablePromise<$models.SidebarItem[] | null> {
    return $Call.ByID(2813498622);
}

/**
 * BatchSetSeries assigns or clears a series for selected books. It does not
 * move files: the managed path currently depends on title/primary author only.
 */
export function BatchSetSeries($in: $models.BatchSeriesUpdate): $CancellablePromise<$models.BatchUpdateResult> {
    return $Call.ByID(1314132227, $in);
}

/**
 * Book returns the full detail for one book.
 */
export function Book(id: number): $CancellablePromise<$models.BookDetail> {
    return $Call.ByID(1347111875, id);
}

/**
 * Books returns all books in the given sort order ("title", "author", "added").
 */
export function Books(sort: string): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(378021392, sort);
}

/**
 * BooksByAuthor returns an author's books.
 */
export function BooksByAuthor(id: number): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(240607566, id);
}

/**
 * BooksByReadingStatus returns books in a given KOReader reading status
 * ("reading", "complete", "abandoned").
 */
export function BooksByReadingStatus(status: string): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(1406624309, status);
}

/**
 * BooksBySeries returns a series' books, in reading order.
 */
export function BooksBySeries(id: number): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(1453195768, id);
}

/**
 * BooksBySmartShelf returns the books currently matching a shelf definition.
 */
export function BooksBySmartShelf(id: number): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(3225881722, id);
}

/**
 * BooksByTag returns the books carrying a tag.
 */
export function BooksByTag(id: number): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(2072736763, id);
}

/**
 * BooksWithoutAuthor returns books that have no author link.
 */
export function BooksWithoutAuthor(): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(1277655111);
}

/**
 * BooksWithoutSeries returns books that are not attached to a series.
 */
export function BooksWithoutSeries(): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(3866900761);
}

/**
 * BooksWithoutTag returns books that carry no tag.
 */
export function BooksWithoutTag(): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(1073537316);
}

/**
 * ChooseAndImport opens a native picker that accepts any mix of ebook files and
 * folders (multiple selection), and imports them. Folders are scanned
 * recursively. Emits an "import:progress" event per file. An empty selection
 * (dialog cancelled) is a no-op.
 */
export function ChooseAndImport(): $CancellablePromise<$models.ImportSummary> {
    return $Call.ByID(1506731901);
}

export function ContentOccurrences(query: string, scope: $models.SearchScope, page: number, perPage: number): $CancellablePromise<$models.ContentOccurrencePage> {
    return $Call.ByID(996457703, query, scope, page, perPage);
}

export function ContentSnippets(query: string, scope: $models.SearchScope, booksLimit: number, hitsPerBook: number): $CancellablePromise<$models.ContentSnippet[] | null> {
    return $Call.ByID(2289333813, query, scope, booksLimit, hitsPerBook);
}

/**
 * DeleteSmartShelf removes a shelf definition.
 */
export function DeleteSmartShelf(id: number): $CancellablePromise<void> {
    return $Call.ByID(386768558, id);
}

/**
 * ImportDiscoverBook downloads a book from a supported discovery provider and
 * imports the EPUB through the normal library pipeline.
 */
export function ImportDiscoverBook(source: string, id: string): $CancellablePromise<$models.ImportSummary> {
    return $Call.ByID(1763671349, source, id);
}

/**
 * ImportGutenbergBook downloads a catalogue book's EPUB and imports it into the
 * library. It re-resolves the download URL from Gutendex by id (rather than
 * trusting a client-supplied URL) and always copies into the managed library,
 * since the download lives in a throwaway temp file. Progress and the summary
 * flow through the normal import events, so the UI refreshes as usual.
 */
export function ImportGutenbergBook(id: number): $CancellablePromise<$models.ImportSummary> {
    return $Call.ByID(1202307301, id);
}

/**
 * ImportPaths imports a mix of files and directories (directories are scanned
 * recursively) using the current import mode. It emits an "import:progress"
 * event per file and an "import:done" event with the summary at the end — the
 * latter lets a drag-and-drop import (which nothing awaits) refresh the view.
 */
export function ImportPaths(paths: string[] | null): $CancellablePromise<$models.ImportSummary> {
    return $Call.ByID(726455477, paths);
}

/**
 * QuickEditRows returns every book as a flat row for the spreadsheet-like
 * editor. It intentionally loads full books so the row contains relations.
 */
export function QuickEditRows(): $CancellablePromise<$models.QuickEditRow[] | null> {
    return $Call.ByID(866761192);
}

/**
 * RegenerateCovers builds a cached thumbnail for every book that lacks one
 * (e.g. PDFs imported before cover extraction existed). Books whose file yields
 * no image are left without a cover.
 */
export function RegenerateCovers(): $CancellablePromise<$models.CoverResult> {
    return $Call.ByID(1789265036);
}

/**
 * ReindexContent extracts text from every indexed ebook file and rebuilds the
 * content FTS index. It can take time on large libraries, so the UI exposes it
 * as an explicit maintenance action.
 */
export function ReindexContent(): $CancellablePromise<$models.ContentReindexResult> {
    return $Call.ByID(1692897598);
}

/**
 * RemoveBook removes a book from the library index. Files stored inside the
 * managed LibraryDir are moved to the system trash first; files outside that
 * tree are left untouched and only disappear from Reliure's index.
 */
export function RemoveBook(id: number): $CancellablePromise<$models.RemoveBookResult> {
    return $Call.ByID(3088526047, id);
}

/**
 * SaveQuickEdits applies changed quick-edit rows. Rows are independent: a
 * validation/file-move failure is reported for that row and does not prevent
 * later rows from saving.
 */
export function SaveQuickEdits(rows: $models.QuickEditRow[] | null): $CancellablePromise<$models.QuickEditSaveResult> {
    return $Call.ByID(793741923, rows);
}

/**
 * SaveSmartShelf creates or updates a dynamic shelf.
 */
export function SaveSmartShelf($in: $models.SmartShelfInput): $CancellablePromise<$models.SmartShelfDetail> {
    return $Call.ByID(1439789288, $in);
}

/**
 * Search returns books matching a full-text query, ranked by relevance.
 */
export function Search(query: string): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(2206755262, query);
}

/**
 * SearchDiscover browses legal ebook providers from the single discovery view.
 * source may be "all", "gutenberg" or "standardebooks".
 */
export function SearchDiscover(source: string, search: string, languages: string, page: number): $CancellablePromise<$models.DiscoverResult> {
    return $Call.ByID(4163992081, source, search, languages, page);
}

/**
 * SearchGutenberg browses the Project Gutenberg catalogue (via Gutendex).
 * languages is a comma-separated list of ISO 639-1 codes (e.g. "fr" or "fr,en").
 */
export function SearchGutenberg(search: string, languages: string, page: number): $CancellablePromise<$models.GutenbergResult> {
    return $Call.ByID(3955102823, search, languages, page);
}

/**
 * SearchOnlineMetadata queries the online providers for editions matching the
 * given hints. Empty hints fall back to the book's own metadata, so the UI can
 * open and search immediately. The language hint only ranks results (preferred
 * language first); it never hides other editions, so the user keeps the choice.
 */
export function SearchOnlineMetadata(bookID: number, title: string, authors: string, isbn: string, language: string): $CancellablePromise<$models.OnlineSearchResult> {
    return $Call.ByID(3651181984, bookID, title, authors, isbn, language);
}

/**
 * SearchScoped returns metadata matches, plus content matches when content
 * search is enabled, constrained to the current library view.
 */
export function SearchScoped(query: string, scope: $models.SearchScope): $CancellablePromise<$models.BookCard[] | null> {
    return $Call.ByID(3379192954, query, scope);
}

/**
 * SeriesGroups returns series tiles for the grouped library view, including a
 * synthetic fallback tile for books without a series.
 */
export function SeriesGroups(): $CancellablePromise<$models.SidebarItem[] | null> {
    return $Call.ByID(1818650967);
}

/**
 * SeriesList returns the sidebar's series list with counts.
 */
export function SeriesList(): $CancellablePromise<$models.SidebarItem[] | null> {
    return $Call.ByID(812942751);
}

/**
 * SetAuthorSort updates an author's sort name (empty clears it, so sends fall
 * back to the display name) and mirrors the change into the given book's file
 * if enabled. Note the author's sort name is shared across all their books.
 */
export function SetAuthorSort(bookID: number, authorID: number, sort: string): $CancellablePromise<$models.BookDetail> {
    return $Call.ByID(4019727117, bookID, authorID, sort);
}

/**
 * SetReadingState records a book's reading progress/status set by hand, so the
 * feature works without ever connecting KOReader. It always wins over the stored
 * value (unlike device sync, which only advances); a later KOReader sync will
 * still only move it forward, never backward.
 */
export function SetReadingState($in: $models.ReadingUpdate): $CancellablePromise<$models.BookDetail> {
    return $Call.ByID(1332077319, $in);
}

/**
 * SetTitleSort updates just a book's sort title (empty clears it) and, if
 * enabled, mirrors it into the ebook file.
 */
export function SetTitleSort(bookID: number, sort: string): $CancellablePromise<$models.BookDetail> {
    return $Call.ByID(789912444, bookID, sort);
}

/**
 * SmartShelf returns one shelf definition.
 */
export function SmartShelf(id: number): $CancellablePromise<$models.SmartShelfDetail> {
    return $Call.ByID(3239525101, id);
}

/**
 * SmartShelves returns all dynamic shelves with live counts.
 */
export function SmartShelves(): $CancellablePromise<$models.SmartShelfSummary[] | null> {
    return $Call.ByID(1867417249);
}

/**
 * Stats returns basic counts for the UI.
 */
export function Stats(): $CancellablePromise<$models.LibraryStats> {
    return $Call.ByID(2363876853);
}

/**
 * TagGroups returns tag tiles for the grouped library view, including a
 * synthetic fallback tile for books without tags.
 */
export function TagGroups(): $CancellablePromise<$models.SidebarItem[] | null> {
    return $Call.ByID(1631548982);
}

/**
 * Tags returns the sidebar's tag list with counts.
 */
export function Tags(): $CancellablePromise<$models.SidebarItem[] | null> {
    return $Call.ByID(4025079207);
}

/**
 * UpdateBook persists editable metadata and moves managed files when the
 * primary author or title changes. The database remains the source of truth:
 * if a file move fails, moved files and metadata are rolled back best-effort.
 */
export function UpdateBook($in: $models.BookUpdate): $CancellablePromise<$models.BookDetail> {
    return $Call.ByID(279100834, $in);
}
