// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as koreaderstats$0 from "../../internal/koreaderstats/models.js";

/**
 * AnnotatedBook groups a book's annotations for the "Annotations" view.
 */
export interface AnnotatedBook {
    "bookId": number;
    "title": string;
    "authors": string;
    "cover": string;
    "annotations": Annotation[] | null;
}

/**
 * Annotation is a KOReader highlight and/or note for the detail view.
 */
export interface Annotation {
    "text": string;
    "note": string;
    "chapter": string;
    "drawer": string;
    "createdAt": string;
}

/**
 * AppSettings is the frontend-facing settings shape (flat, JSON-friendly).
 */
export interface AppSettings {
    /**
     * "copy" | "reference"
     */
    "importMode": string;
    "libraryDir": string;
    "remotePathTemplate": string;
    "opdsEnabled": boolean;
    "opdsPort": number;
    "writeMetadataToFile": boolean;
    "theme": string;
    "language": string;
    "koreaderSyncDir": string;
    "featureDiscover": boolean;
    "featureSmartShelves": boolean;
    "watchFolderEnabled": boolean;
    "watchFolderDir": string;
    "watchFolderDelaySeconds": number;
    "watchFolderDeleteSource": boolean;
    "contentSearchEnabled": boolean;
    "contentSearchContext": string;
    "readingStatsEnabled": boolean;
}

/**
 * ApplyMetadataInput carries the user's field-by-field choices as a ready-made
 * BookUpdate, plus an optional cover URL to download and apply.
 */
export interface ApplyMetadataInput {
    "book": BookUpdate;
    "coverUrl": string;
}

/**
 * BatchSeriesUpdate assigns one series to several books. When SeriesIndexStart
 * is set, books receive consecutive indices in the order provided by IDs.
 */
export interface BatchSeriesUpdate {
    "ids": number[] | null;
    "series": string;
    "seriesIndexStart": string;
}

/**
 * BatchUpdateResult summarizes a metadata batch operation.
 */
export interface BatchUpdateResult {
    "updated": number;
}

/**
 * BookCard is the compact shape shown in the grid/list. Covers are referenced
 * by URL (served by the asset handler), never inlined as base64.
 */
export interface BookCard {
    "id": number;
    "title": string;
    "authors": string;
    "series": string;
    "seriesIndex": number;
    "cover": string;
    "formats": string[] | null;
}

/**
 * BookDetail is the full metadata for the detail view.
 */
export interface BookDetail {
    "id": number;
    "title": string;
    "titleSort": string;
    "authors": Contributor[] | null;
    "series": string;
    "seriesIndex": number;
    "description": string;
    "language": string;
    "isbn": string;
    "published": string;
    "tags": string[] | null;
    "cover": string;
    "files": FileInfo[] | null;
    "addedAt": string;
    "updatedAt": string;
    "remotePathOverrideEnabled": boolean;
    "remotePathOverride": string;
    "remotePath": string;

    /**
     * Reading progress mirrored from KOReader (zero/empty when never synced).
     */
    "percent": number;
    "pages": number;
    "readingStatus": string;
    "lastReadAt": string;

    /**
     * 1..5 star rating (0 = unrated)
     */
    "rating": number;

    /**
     * true if set by hand in Reliure
     */
    "ratingManual": boolean;
    "annotations": Annotation[] | null;
}

/**
 * BookUpdate is the editable metadata payload sent by the frontend. Files are
 * intentionally excluded; they are moved only as a consequence of title/author
 * changes for managed-library books.
 */
export interface BookUpdate {
    "id": number;
    "title": string;
    "titleSort": string;
    "authors": string[] | null;
    "series": string;
    "seriesIndex": string;
    "description": string;
    "language": string;
    "isbn": string;
    "published": string;
    "tags": string[] | null;
    "remotePathOverrideEnabled": boolean;
    "remotePathOverride": string;
}

/**
 * CalibreSendProgress is emitted once per book while sending to the device.
 */
export interface CalibreSendProgress {
    "total": number;
    "done": number;
    "title": string;
    "ok": boolean;
    "error"?: string;
}

/**
 * CalibreStatus is the frontend-facing push-server state.
 */
export interface CalibreStatus {
    "running": boolean;
    "connected": boolean;
    "device": string;
    "port": number;

    /**
     * Address is the LAN host:port KOReader can be pointed at manually if
     * UDP auto-discovery does not work (e.g. across subnets).
     */
    "address": string;

    /**
     * LastDevice is the connected device name, or the last one seen when
     * disconnected. It signals the UI that cached on-device presence is available
     * (the `.reliure` inventory) even without a live connection.
     */
    "lastDevice": string;
}

export interface ContentDashboard {
    "enabled": boolean;
    "indexedBooks": number;
    "emptyBooks": number;
    "failedBooks": number;
    "pendingBooks": number;
    "indexedChars": number;
}

export interface ContentOccurrencePage {
    "total": number;
    "page": number;
    "perPage": number;
    "totalPages": number;
    "items": ContentSnippet[] | null;
}

export interface ContentReindexResult {
    "total": number;
    "indexed": number;
    "empty": number;
    "failed": number;
}

export interface ContentSnippet {
    "bookId": number;
    "title": string;
    "authors": string;
    "series": string;
    "seriesIndex": number;
    "cover": string;
    "page": number;
    "snippet": string;
    "more": number;
}

/**
 * Contributor is a named author/role pair for the detail view.
 */
export interface Contributor {
    "id": number;
    "name": string;
    "sortName": string;
    "role": string;
}

/**
 * CoverResult summarizes a cover-regeneration run.
 */
export interface CoverResult {
    "scanned": number;
    "updated": number;
}

/**
 * Dashboard is the full analytics payload.
 */
export interface Dashboard {
    "books": number;
    "authors": number;
    "series": number;
    "tags": number;
    "files": number;
    "totalSize": number;
    "onDevice": number;
    "annotations": number;
    "reading": ReadingBreakdown;
    "formats": NameCount[] | null;
    "languages": NameCount[] | null;
    "topAuthors": NameCount[] | null;
    "topTags": NameCount[] | null;
    "addedByMonth": NameCount[] | null;
    "recent": BookCard[] | null;
    "content": ContentDashboard;

    /**
     * ReadingStats holds KOReader reading-time aggregates when the feature is on
     * and stats have been fetched; nil otherwise.
     */
    "readingStats": koreaderstats$0.ReadingStats | null;
}

/**
 * DeviceBookState tells the UI whether a local book is known to be on the
 * currently connected device according to the last `.reliure` inventory.
 */
export interface DeviceBookState {
    "bookId": number;

    /**
     * "unknown" | "absent" | "present"
     */
    "status": string;
    "remotePath"?: string;
    "sentAt"?: string;
}

/**
 * DiscoverBook is the source-agnostic shape used by the "Découvrir" view.
 */
export interface DiscoverBook {
    "source": string;
    "id": string;
    "title": string;
    "authors": string[] | null;
    "languages": string[] | null;
    "subjects": string[] | null;
    "cover": string;
    "hasEpub": boolean;
}

/**
 * DiscoverResult is a page of discovery results across one or more providers.
 */
export interface DiscoverResult {
    "count": number;
    "hasNext": boolean;
    "hasPrevious": boolean;
    "page": number;
    "books": DiscoverBook[] | null;
}

/**
 * FileInfo describes one file backing a book.
 */
export interface FileInfo {
    "format": string;
    "size": number;
    "path": string;
    "sha256": string;
    "addedAt": string;
}

/**
 * GutenbergBook is the JSON-friendly shape of a catalogue entry for the
 * "Découvrir" view.
 */
export interface GutenbergBook {
    "id": number;
    "title": string;
    "authors": string[] | null;
    "languages": string[] | null;
    "subjects": string[] | null;
    "cover": string;
    "hasEpub": boolean;
}

/**
 * GutenbergResult is a page of catalogue results.
 */
export interface GutenbergResult {
    "count": number;
    "hasNext": boolean;
    "hasPrevious": boolean;
    "page": number;
    "books": GutenbergBook[] | null;
}

/**
 * ImportProgress is the per-file payload sent on the "import:progress" event.
 */
export interface ImportProgress {
    "total": number;
    "done": number;
    "title": string;
    "outcome": string;
    "bookId": number;
    "error"?: string;
}

/**
 * ImportSummary is returned when an import finishes.
 */
export interface ImportSummary {
    "total": number;
    "imported": number;
    "attached": number;
    "duplicates": number;
    "failed": number;
}

/**
 * KoreaderSyncResult summarizes a sync run.
 */
export interface KoreaderSyncResult {
    "dir": string;
    "scanned": number;
    "matched": number;
    "unmatched": number;
    "withProgress": number;
    "annotations": number;
}

/**
 * LibraryStats is a small snapshot for the UI.
 */
export interface LibraryStats {
    "books": number;
}

/**
 * NameCount is a labelled magnitude for the dashboard's bar charts.
 */
export interface NameCount {
    "name": string;
    "count": number;
}

/**
 * OPDSStatus is the frontend-facing server state.
 */
export interface OPDSStatus {
    "enabled": boolean;
    "running": boolean;
    "port": number;
    "url": string;
    "error"?: string;
}

/**
 * OnlineCandidate is one online edition offered to the user, JSON-friendly. It
 * carries every field so the frontend can let the user cherry-pick and edit
 * each one before applying (e.g. keep the French description, drop an author in
 * "Last, First" form).
 */
export interface OnlineCandidate {
    "id": string;
    "source": string;
    "title": string;
    "subtitle": string;
    "authors": string[] | null;
    "publisher": string;
    "published": string;
    "description": string;
    "language": string;
    "isbn": string;
    "series": string;
    "seriesIndex": string;
    "tags": string[] | null;
    "coverUrl": string;
    "pageCount": number;
}

/**
 * OnlineSearchResult wraps the ranked candidates plus the effective query, so
 * the UI can show what it actually searched for.
 */
export interface OnlineSearchResult {
    "query": string;
    "candidates": OnlineCandidate[] | null;
}

/**
 * PingResult is what Ping returns. Exposing a struct (rather than a bare
 * string) exercises the binding generator's model generation end to end and
 * gives the UI something concrete to display.
 */
export interface PingResult {
    "message": string;
    "goVersion": string;
    "platform": string;
}

/**
 * QuickEditRow is one editable row in the spreadsheet-like metadata editor.
 * Multi-value fields are comma- or semicolon-separated strings for ergonomic
 * paste/edit workflows.
 */
export interface QuickEditRow {
    "id": number;
    "title": string;
    "titleSort": string;
    "authors": string;
    "series": string;
    "seriesIndex": string;
    "tags": string;
    "language": string;
    "published": string;
    "isbn": string;
    "remotePathOverrideEnabled": boolean;
    "remotePathOverride": string;
    "updatedAt": string;
}

/**
 * QuickEditRowError reports a failed row without aborting the whole batch.
 */
export interface QuickEditRowError {
    "id": number;
    "error": string;
}

/**
 * QuickEditSaveResult summarizes a quick-edit save.
 */
export interface QuickEditSaveResult {
    "updated": number;
    "failed": number;
    "errors": QuickEditRowError[] | null;
    "rows": QuickEditSavedBook[] | null;
}

/**
 * QuickEditSavedBook carries fresh timestamps for rows saved successfully.
 */
export interface QuickEditSavedBook {
    "id": number;
    "updatedAt": string;
}

/**
 * ReadingBreakdown splits the library by reading status (unread = everything
 * not tracked or explicitly new).
 */
export interface ReadingBreakdown {
    "complete": number;
    "reading": number;
    "abandoned": number;
    "unread": number;
}

/**
 * ReadingCard is the compact per-book reading state for grid overlays.
 */
export interface ReadingCard {
    "bookId": number;
    "percent": number;
    "pages": number;
    "status": string;
    "annotations": number;
}

/**
 * ReadingStatsFetch summarizes a fetch of the statistics database.
 */
export interface ReadingStatsFetch {
    "found": boolean;
    "lpath": string;
    "bytes": number;
    "tried": number;
    "parsed": boolean;
    "totalSeconds": number;
    "daysRead": number;
    "error"?: string;
}

/**
 * ReadingStatsProbe reports whether KOReader's statistics database could be
 * fetched over the Calibre connection, and from which relative path.
 */
export interface ReadingStatsProbe {
    "found": boolean;

    /**
     * the candidate path that returned the file
     */
    "lpath": string;
    "bytes": number;

    /**
     * true when the bytes start with the SQLite magic
     */
    "valid": boolean;
    "tried": number;
}

/**
 * ReadingStatusCounts is the number of books per reading status, for the sidebar.
 */
export interface ReadingStatusCounts {
    "reading": number;
    "complete": number;
    "abandoned": number;
}

/**
 * ReadingUpdate is a manual reading-state edit from the UI. Progress can be given
 * as a percentage or as a page (with an optional total). Clear removes tracking.
 */
export interface ReadingUpdate {
    "bookId": number;

    /**
     * "reading" | "complete" | "abandoned" | ""
     */
    "status": string;

    /**
     * 0..1
     */
    "percent": number;

    /**
     * current page (optional)
     */
    "page": number;

    /**
     * total pages (optional)
     */
    "totalPages": number;

    /**
     * true → "mark as unread" (delete state)
     */
    "clear": boolean;
}

/**
 * RemoveBookResult describes how a removed book was handled.
 */
export interface RemoveBookResult {
    "removedFromIndex": number;
    "trashedFiles": number;
    "keptFiles": number;
}

export interface SearchScope {
    "kind": string;
    "id": number;
}

/**
 * SendResult summarizes a send-to-device run.
 */
export interface SendResult {
    "sent": number;
    "failed": number;
    "inventorySent": boolean;
    "inventoryError"?: string;
}

/**
 * SidebarItem is a named entry (author/series/tag) with a book count.
 */
export interface SidebarItem {
    "id": number;
    "name": string;
    "count": number;
}

/**
 * SmartShelfDetail is the full shelf definition plus its current book count.
 */
export interface SmartShelfDetail {
    "id": number;
    "name": string;
    "match": string;
    "rules": SmartShelfRule[] | null;
    "position": number;
    "count": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * SmartShelfInput creates or updates a smart shelf.
 */
export interface SmartShelfInput {
    "id": number;
    "name": string;
    "match": string;
    "rules": SmartShelfRule[] | null;
    "position": number;
}

/**
 * SmartShelfRule is one UI-editable predicate in a dynamic shelf.
 */
export interface SmartShelfRule {
    "field": string;
    "operator": string;
    "value": string;
}

/**
 * SmartShelfSummary is used by the sidebar and shelf list.
 */
export interface SmartShelfSummary {
    "id": number;
    "name": string;
    "count": number;
}

export interface WatchFolderStatus {
    "enabled": boolean;
    "running": boolean;
    "dir": string;
    "delaySeconds": number;
    "deleteSource": boolean;
    "lastError"?: string;
}
