// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppSettings is the frontend-facing settings shape (flat, JSON-friendly).
 */
export interface AppSettings {
    /**
     * "copy" | "reference"
     */
    "importMode": string;
    "libraryDir": string;
}

/**
 * BookCard is the compact shape shown in the grid/list. Covers are referenced
 * by URL (served by the asset handler), never inlined as base64.
 */
export interface BookCard {
    "id": number;
    "title": string;
    "authors": string;
    "series": string;
    "seriesIndex": number;
    "cover": string;
    "formats": string[] | null;
}

/**
 * BookDetail is the full metadata for the detail view.
 */
export interface BookDetail {
    "id": number;
    "title": string;
    "authors": Contributor[] | null;
    "series": string;
    "seriesIndex": number;
    "description": string;
    "language": string;
    "isbn": string;
    "published": string;
    "tags": string[] | null;
    "cover": string;
    "files": FileInfo[] | null;
}

/**
 * Contributor is a named author/role pair for the detail view.
 */
export interface Contributor {
    "name": string;
    "role": string;
}

/**
 * FileInfo describes one file backing a book.
 */
export interface FileInfo {
    "format": string;
    "size": number;
    "path": string;
}

/**
 * ImportProgress is the per-file payload sent on the "import:progress" event.
 */
export interface ImportProgress {
    "total": number;
    "done": number;
    "title": string;
    "outcome": string;
    "bookId": number;
    "error"?: string;
}

/**
 * ImportSummary is returned when an import finishes.
 */
export interface ImportSummary {
    "total": number;
    "imported": number;
    "attached": number;
    "duplicates": number;
    "failed": number;
}

/**
 * LibraryStats is a small snapshot for the UI.
 */
export interface LibraryStats {
    "books": number;
}

/**
 * PingResult is what Ping returns. Exposing a struct (rather than a bare
 * string) exercises the binding generator's model generation end to end and
 * gives the UI something concrete to display.
 */
export interface PingResult {
    "message": string;
    "goVersion": string;
    "platform": string;
}

/**
 * SidebarItem is a named entry (author/series/tag) with a book count.
 */
export interface SidebarItem {
    "id": number;
    "name": string;
    "count": number;
}
