// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppSettings is the frontend-facing settings shape (flat, JSON-friendly).
 */
export interface AppSettings {
    /**
     * "copy" | "reference"
     */
    "importMode": string;
    "libraryDir": string;
    "remotePathTemplate": string;
    "opdsEnabled": boolean;
    "opdsPort": number;
    "writeMetadataToFile": boolean;
    "theme": string;
}

/**
 * BatchSeriesUpdate assigns one series to several books. When SeriesIndexStart
 * is set, books receive consecutive indices in the order provided by IDs.
 */
export interface BatchSeriesUpdate {
    "ids": number[] | null;
    "series": string;
    "seriesIndexStart": string;
}

/**
 * BatchUpdateResult summarizes a metadata batch operation.
 */
export interface BatchUpdateResult {
    "updated": number;
}

/**
 * BookCard is the compact shape shown in the grid/list. Covers are referenced
 * by URL (served by the asset handler), never inlined as base64.
 */
export interface BookCard {
    "id": number;
    "title": string;
    "authors": string;
    "series": string;
    "seriesIndex": number;
    "cover": string;
    "formats": string[] | null;
}

/**
 * BookDetail is the full metadata for the detail view.
 */
export interface BookDetail {
    "id": number;
    "title": string;
    "titleSort": string;
    "authors": Contributor[] | null;
    "series": string;
    "seriesIndex": number;
    "description": string;
    "language": string;
    "isbn": string;
    "published": string;
    "tags": string[] | null;
    "cover": string;
    "files": FileInfo[] | null;
    "addedAt": string;
    "updatedAt": string;
    "remotePathOverrideEnabled": boolean;
    "remotePathOverride": string;
    "remotePath": string;
}

/**
 * BookUpdate is the editable metadata payload sent by the frontend. Files are
 * intentionally excluded; they are moved only as a consequence of title/author
 * changes for managed-library books.
 */
export interface BookUpdate {
    "id": number;
    "title": string;
    "titleSort": string;
    "authors": string[] | null;
    "series": string;
    "seriesIndex": string;
    "description": string;
    "language": string;
    "isbn": string;
    "published": string;
    "tags": string[] | null;
    "remotePathOverrideEnabled": boolean;
    "remotePathOverride": string;
}

/**
 * CalibreSendProgress is emitted once per book while sending to the device.
 */
export interface CalibreSendProgress {
    "total": number;
    "done": number;
    "title": string;
    "ok": boolean;
    "error"?: string;
}

/**
 * CalibreStatus is the frontend-facing push-server state.
 */
export interface CalibreStatus {
    "running": boolean;
    "connected": boolean;
    "device": string;
    "port": number;

    /**
     * Address is the LAN host:port KOReader can be pointed at manually if
     * UDP auto-discovery does not work (e.g. across subnets).
     */
    "address": string;
}

/**
 * Contributor is a named author/role pair for the detail view.
 */
export interface Contributor {
    "id": number;
    "name": string;
    "sortName": string;
    "role": string;
}

/**
 * CoverResult summarizes a cover-regeneration run.
 */
export interface CoverResult {
    "scanned": number;
    "updated": number;
}

/**
 * FileInfo describes one file backing a book.
 */
export interface FileInfo {
    "format": string;
    "size": number;
    "path": string;
    "sha256": string;
    "addedAt": string;
}

/**
 * ImportProgress is the per-file payload sent on the "import:progress" event.
 */
export interface ImportProgress {
    "total": number;
    "done": number;
    "title": string;
    "outcome": string;
    "bookId": number;
    "error"?: string;
}

/**
 * ImportSummary is returned when an import finishes.
 */
export interface ImportSummary {
    "total": number;
    "imported": number;
    "attached": number;
    "duplicates": number;
    "failed": number;
}

/**
 * LibraryStats is a small snapshot for the UI.
 */
export interface LibraryStats {
    "books": number;
}

/**
 * OPDSStatus is the frontend-facing server state.
 */
export interface OPDSStatus {
    "enabled": boolean;
    "running": boolean;
    "port": number;
    "url": string;
    "error"?: string;
}

/**
 * PingResult is what Ping returns. Exposing a struct (rather than a bare
 * string) exercises the binding generator's model generation end to end and
 * gives the UI something concrete to display.
 */
export interface PingResult {
    "message": string;
    "goVersion": string;
    "platform": string;
}

/**
 * RemoveBookResult describes how a removed book was handled.
 */
export interface RemoveBookResult {
    "removedFromIndex": number;
    "trashedFiles": number;
    "keptFiles": number;
}

/**
 * SendResult summarizes a send-to-device run.
 */
export interface SendResult {
    "sent": number;
    "failed": number;
}

/**
 * SidebarItem is a named entry (author/series/tag) with a book count.
 */
export interface SidebarItem {
    "id": number;
    "name": string;
    "count": number;
}
