// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OPDSService controls the local OPDS pull server exposed to KOReader.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * SetEnabled persists the on/off preference and starts or stops the server.
 */
export function SetEnabled(enabled: boolean): $CancellablePromise<$models.OPDSStatus> {
    return $Call.ByID(1357012470, enabled);
}

/**
 * SetPort persists the TCP port. If OPDS is running, it is restarted on the new
 * port immediately.
 */
export function SetPort(port: number): $CancellablePromise<$models.OPDSStatus> {
    return $Call.ByID(96696414, port);
}

/**
 * Status returns the persisted preference plus runtime state.
 */
export function Status(): $CancellablePromise<$models.OPDSStatus> {
    return $Call.ByID(2144970657);
}
