// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes user preferences to the frontend. The key preference
 * is the import mode: "copy" (Reliure manages copies in its library folder) or
 * "reference" (files are indexed where they already live).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChooseLibraryFolder opens a native directory picker to set the managed
 * library location (used in copy mode). A cancelled dialog leaves it unchanged.
 */
export function ChooseLibraryFolder(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1181027004);
}

/**
 * Get returns the current settings.
 */
export function Get(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(710695688);
}

/**
 * SetImportMode switches between "copy" and "reference". An unknown value is
 * normalized to "copy" by the store.
 */
export function SetImportMode(mode: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(4033158262, mode);
}

/**
 * SetRemotePathTemplate stores the template used for future KOReader sends.
 */
export function SetRemotePathTemplate(tmpl: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3717326007, tmpl);
}

/**
 * SetTheme sets the UI appearance: "system", "light" or "dark".
 */
export function SetTheme(theme: string): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(466396097, theme);
}

/**
 * SetWriteMetadataToFile toggles writing edited metadata back into ebook files
 * on save.
 */
export function SetWriteMetadataToFile(enabled: boolean): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2744555517, enabled);
}
