// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StatsService computes the analytics dashboard. It is read-only and assembles
 * its answer from a handful of aggregate queries plus the device inventory.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Dashboard gathers every statistic shown on the dashboard.
 */
export function Dashboard(): $CancellablePromise<$models.Dashboard> {
    return $Call.ByID(3956003610);
}
