// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WatchFolderService imports new ebook files dropped in a configured folder.
 * It intentionally reuses LibraryService.ImportPaths so automatic imports follow
 * the same mode, deduplication, cover cache and UI events as manual imports.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ChooseFolder(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2669535431);
}

export function ClearFolder(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1525609279);
}

export function SetDelaySeconds(delay: number): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(4018600826, delay);
}

export function SetDeleteSource(enabled: boolean): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(4264825888, enabled);
}

export function SetEnabled(enabled: boolean): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(959956623, enabled);
}

export function Status(): $CancellablePromise<$models.WatchFolderStatus> {
    return $Call.ByID(2487797116);
}
