// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BookTime is how long a book was read and when it was last opened.
 */
export interface BookTime {
    "title": string;
    "authors": string;
    "seconds": number;

    /**
     * YYYY-MM-DD, local time
     */
    "lastRead": string;
}

/**
 * DayCount is reading time (seconds) on a given local calendar day.
 */
export interface DayCount {
    /**
     * YYYY-MM-DD, local time
     */
    "date": string;
    "seconds": number;
}

/**
 * ReadingStats is the aggregated view of a KOReader statistics database.
 */
export interface ReadingStats {
    "totalSeconds": number;
    "totalPages": number;
    "daysRead": number;
    "books": number;
    "longestDay": DayCount;

    /**
     * length 7, index 0 = Monday … 6 = Sunday
     */
    "byWeekday": number[] | null;

    /**
     * length 24, local hour of day
     */
    "byHour": number[] | null;

    /**
     * chronological
     */
    "byDay": DayCount[] | null;

    /**
     * most-read books by time
     */
    "topBooks": BookTime[] | null;

    /**
     * DayBooks maps a local day (YYYY-MM-DD) to the books read that day and for
     * how long, most-read first. Bounded to a recent window (see dayBooksWindow).
     */
    "dayBooks": { [_ in string]?: BookTime[] | null } | null;

    /**
     * MonthBooks maps a local month (YYYY-MM) to the books read that month, in the
     * order they were first opened. Covers all history (for the year selector).
     */
    "monthBooks": { [_ in string]?: BookTime[] | null } | null;

    /**
     * set by the caller when cached
     */
    "fetchedAt": string;
}
